export { default as App } from './App'
export { default as Router } from './Router'
export { default as NavBar } from './NavBar'
export { default as DashboardSlide } from './DashboardSlide'
export { default as Dashboard } from './Dashboard'
export { default as UploadSlide } from './UploadSlide'
